# Generated by Django 4.0 on 2021-12-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagemodel',
            name='outage_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outagemodel',
            name='outage_time',
            field=models.IntegerField(default=0),
        ),
    ]
